from selenium import webdriver

driver = webdriver.Chrome(executable_path=r'C:\driver_chrome\chromedriver.exe')
driver.get('http://demo-store.seleniumacademy.com/')
action = driver.find_element_by_xpath('//*[@id="header"]/div/div[2]/div/a/span[2]')
action.click()
action = driver.find_element_by_xpath('//*[@id="header-account"]/div/ul/li[5]/a')
action.click()
action = driver.find_element_by_name('firstname')
action.send_keys('This')
action = driver.find_element_by_name('middlename')
action.send_keys('Is')
action = driver.find_element_by_name('lastname')
action.send_keys('Test')
action = driver.find_element_by_name('email')
action.send_keys('thisistest@email.com')
action = driver.find_element_by_name('password')
action.send_keys('p455w0rd')
action = driver.find_element_by_name('confirmation')
action.send_keys('p455w0rd')
action = driver.find_element_by_id('is_subscribed')
action.click()
action = driver.find_element_by_xpath('//*[@id="form-validate"]/div[2]/button')
action.click()
